// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnalysisResult 保存视频分析的完整结果
type AnalysisResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 被分析的视频文件路径
	VideoFile string `protobuf:"bytes,1,opt,name=video_file,json=videoFile,proto3" json:"video_file,omitempty"`
	// 视频帧率
	Fps float64 `protobuf:"fixed64,2,opt,name=fps,proto3" json:"fps,omitempty"`
	// 视频宽度（像素）
	Width int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	// 视频高度（像素）
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// 视频总帧数
	TotalFrames int32 `protobuf:"varint,5,opt,name=total_frames,json=totalFrames,proto3" json:"total_frames,omitempty"`
	// 自动计算的建议阈值
	SuggestedThreshold float64 `protobuf:"fixed64,6,opt,name=suggested_threshold,json=suggestedThreshold,proto3" json:"suggested_threshold,omitempty"`
	// 每一帧的差异像素数量
	DiffCounts    []uint32 `protobuf:"varint,7,rep,packed,name=diff_counts,json=diffCounts,proto3" json:"diff_counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_proto_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisResult) GetVideoFile() string {
	if x != nil {
		return x.VideoFile
	}
	return ""
}

func (x *AnalysisResult) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *AnalysisResult) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AnalysisResult) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AnalysisResult) GetTotalFrames() int32 {
	if x != nil {
		return x.TotalFrames
	}
	return 0
}

func (x *AnalysisResult) GetSuggestedThreshold() float64 {
	if x != nil {
		return x.SuggestedThreshold
	}
	return 0
}

func (x *AnalysisResult) GetDiffCounts() []uint32 {
	if x != nil {
		return x.DiffCounts
	}
	return nil
}

var File_proto_analysis_proto protoreflect.FileDescriptor

const file_proto_analysis_proto_rawDesc = "" +
	"\n" +
	"\x14proto/analysis.proto\x12\x04vcmp\"\xe4\x01\n" +
	"\x0eAnalysisResult\x12\x1d\n" +
	"\n" +
	"video_file\x18\x01 \x01(\tR\tvideoFile\x12\x10\n" +
	"\x03fps\x18\x02 \x01(\x01R\x03fps\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12!\n" +
	"\ftotal_frames\x18\x05 \x01(\x05R\vtotalFrames\x12/\n" +
	"\x13suggested_threshold\x18\x06 \x01(\x01R\x12suggestedThreshold\x12\x1f\n" +
	"\vdiff_counts\x18\a \x03(\rR\n" +
	"diffCountsB\fZ\n" +
	"vcmp/protob\x06proto3"

var (
	file_proto_analysis_proto_rawDescOnce sync.Once
	file_proto_analysis_proto_rawDescData []byte
)

func file_proto_analysis_proto_rawDescGZIP() []byte {
	file_proto_analysis_proto_rawDescOnce.Do(func() {
		file_proto_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)))
	})
	return file_proto_analysis_proto_rawDescData
}

var file_proto_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_analysis_proto_goTypes = []any{
	(*AnalysisResult)(nil), // 0: vcmp.AnalysisResult
}
var file_proto_analysis_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analysis_proto_init() }
func file_proto_analysis_proto_init() {
	if File_proto_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_analysis_proto_goTypes,
		DependencyIndexes: file_proto_analysis_proto_depIdxs,
		MessageInfos:      file_proto_analysis_proto_msgTypes,
	}.Build()
	File_proto_analysis_proto = out.File
	file_proto_analysis_proto_goTypes = nil
	file_proto_analysis_proto_depIdxs = nil
}
